//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaselineMedicalExaminationCalculation.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaselineMedicalExaminationCalculation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на N п/п;Участие врачей-специалистов &lt;3&gt;, &lt;4&gt;, &lt;5&gt;;Лабораторные и функциональные исследования &lt;3&gt;, &lt;4&gt;
        ///1.1.1.;Оториноларинголог;!Специфическая аллергодиагностика
        ///;Дерматовенеролог;Спирометрия с бронходилятационной пробой!
        ///;!Офтальмолог;
        ///;!Аллерголог;
        ///1.1.2.;Дерматовенеролог;!УЗИ органов-мишеней
        ///;Оториноларинголог;Рентгенография грудной клетки в двух проекциях
        ///;!Онколог;
        ///;!Уролог;
        ///1.1.3.;Хирург;УЗИ органов малого таза
        ///;!Уролог;
        ///;!Эндокринолог;
        ///;!Онколог;
        ///1.1.4.1.;Оториноларинголог;Спирометрия
        ///;Дер [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string _302part1_new {
            get {
                return ResourceManager.GetString("_302part1_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование работ и профессий;Участие врачей-специалистов &lt;1&gt;, &lt;2&gt;, &lt;3&gt;;Лабораторные и функциональные исследования &lt;1&gt;, &lt;2&gt;
        ///1. Работы на высоте, верхолазные работы &lt;5&gt;, а также работы по обслуживанию подъемных сооружений, включая:;Невролог;Острота зрения
        ///;Офтальмолог;Поля зрения
        ///;Хирург;Аудиометрия
        ///;Оториноларинголог (только для верхолазных работ);Исследование вестибулярного анализатора
        ///1.1. Работы в качестве крановщика (машиниста крана);Невролог;Острота зрения
        ///;Офтальмолог;Поля зрения
        ///;Хирург;Аудио [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string _302part2_new {
            get {
                return ResourceManager.GetString("_302part2_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на для_всех_1;802000;Диспансерный прием врача-терапевта при обязательном предварительном/периодическом медицинском осмотре (обследовании) (для коллектива от 1 до 50 человек)
        ///для_всех_2;810000;Диспансерный прием врача-психиатра при обязательном предварительном/периодическом медицинском осмотре (обследовании) (для коллектива от 1 до 50 человек)
        ///для_всех_3;811000;Диспансерный прием врача психиатра-нарколога при обязательном предварительном/периодическом медицинском осмотре (обследовании) (для коллектива от 1 до [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string necesserily {
            get {
                return ResourceManager.GetString("necesserily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код услуги ;Наименование заголовка/услуги;  Цена услуги  Н.Новгород 
        ///800000.1;Забор крови на лабораторное исследование при обязательном предварительном/периодическом медицинском осмотре (обследовании) (для коллектива от 1 до 50 человек);5
        ///800000.2;Забор крови на лабораторное исследование при обязательном предварительном/периодическом медицинском осмотре (обследовании) (для коллектива от 51 до 100 человек);5
        ///800000.3;Забор крови на лабораторное исследование при обязательном предварительном/периодическом м [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string price_new {
            get {
                return ResourceManager.GetString("price_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование по 302 приказу (вместе с опциональными);Код группы услуг;Комментарий;Наименование по прайсу
        ///Аллерголог;817000;;Диспансерный прием врача аллерголога-иммунолога при обязательном предварительном/периодическом медицинском осмотре (обследовании) (для коллектива от 1 до 50 человек)
        ///Врач по водолазной медицине;;нет специалиста;
        ///Дерматовенеролог;806000;;Диспансерный прием врача-дерматовенеролога при обязательном предварительном/периодическом медицинском осмотре (обследовании) (для коллектива от 1 до [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string service_matching_new {
            get {
                return ResourceManager.GetString("service_matching_new", resourceCulture);
            }
        }
    }
}
